# Tensors: The Core of PyTorch

You've seen that the journey of building a neural network begins with data. Before you can design a model or start the training process, you must gather your information and prepare it in a format the model can understand. In PyTorch, that fundamental format is the **tensor**. Tensors are more than just data containers; they are optimized for the mathematical operations that power deep learning.

Mastering tensors is a vital step. Many of the most common errors encountered when building models are related to tensor shapes, types, or dimensions. This lab is designed to give you a solid foundation in tensor manipulation, providing you with the skills to handle data effectively and debug issues with confidence.

In this lab, you will learn how to:

* Create tensors from different data sources like Python lists and NumPy arrays.

* Reshape and manipulate tensor dimensions to prepare data for model inputs.

* Use indexing and slicing techniques to access and filter specific parts of your data.

* Perform the mathematical and logical operations that form the basis of all neural network computations.

By the end of this notebook, you will have the practical skills needed to confidently manage the data for any PyTorch project.

In [1]:
import torch
import numpy as np
import pandas as pd

## 1 - Tensor Creation

The first step in any machine learning pipeline is getting your data ready for the model. In PyTorch, this means loading your data into tensors. You will find that there are several convenient ways to create tensors, whether your data is already in another format or you need to generate it from scratch.

### 1.1 From Existing Data Structures

Often, your raw data will be in a common format like a Python list, a NumPy array, or a pandas DataFrame. PyTorch provides straightforward functions to convert these structures into tensors, making the data preparation stage more efficient.

* `torch.tensor()`: This function takes input such as a Python list to convert it into a tensor.

**Note:** The type of numbers you use matters. If you use integers, PyTorch stores them as integers. If you include decimals, they'll be stored as floating point values.

In [3]:
# From python lists
x = torch.tensor([1,2,3])
print("from python lists: ",x)
print("Tensor Data Types: ",x.dtype)

from python lists:  tensor([1, 2, 3])
Tensor Data Types:  torch.int64



* `torch.from_numpy()`: Converts a NumPy array into a PyTorch tensor.

In [4]:
# From a NumPy array
numpy_array = np.array([[1,2,3],[4,5,6]])
torch_tensor_from_numpy = torch.tensor(numpy_array)

print("TENSOR FROM NUMPY:\n\n",torch_tensor_from_numpy)

TENSOR FROM NUMPY:

 tensor([[1, 2, 3],
        [4, 5, 6]])



* **From a pandas DataFrame**: Pandas is a Python library for working with data organized in rows and columns, like a CSV file or spreadsheet. A DataFrame is pandas' main data structure for storing this kind of tabular data. DataFrames are one of the most common ways to load and explore datasets in machine learning, especially when reading CSV files. There isn't a direct function to convert a DataFrame to a tensor. The standard method is to extract the data from the DataFrame into a NumPy array using the `.values` attribute, and then convert that array into a tensor using `torch.tensor()`.

In [5]:
# From pandas DataFrame
# REad the data from the CSV file into a DataFrame
df = pd.read_csv('./data.csv')

# Extract the data as a Numpy array from the DataFrame
all_values = df.values

# Convert the DataFrame's values to a pytorch tenso
tensor_from_df = torch.tensor(all_values)

print("ORIGINAL DATAFRAME\n\n",df)
print("\nRESULTING TENSOR:\n\n",tensor_from_df)
print("\nTENSOR DATA TYPE:",tensor_from_df.dtype)

ORIGINAL DATAFRAME

    distance_miles  delivery_time_minutes
0            1.60                   7.22
1           13.09                  32.41
2            6.97                  17.47

RESULTING TENSOR:

 tensor([[ 1.6000,  7.2200],
        [13.0900, 32.4100],
        [ 6.9700, 17.4700]], dtype=torch.float64)

TENSOR DATA TYPE: torch.float64


### 1.2 - With Predefined Values

Sometimes you need to create tensors for specific purposes, like initializing a model's weights and biases before training begins. PyTorch allows you to quickly generate tensors filled with placeholder values like zeros, ones, or random numbers, which is useful for testing and setup.

* `torch.zeros()`: Creates a tensor filled with zeros of the specified dimensions.

In [6]:
# All zeros
zeros = torch.zeros(2,3)
print("TENSOR WITH ZEROS:\n\n",zeros)

TENSOR WITH ZEROS:

 tensor([[0., 0., 0.],
        [0., 0., 0.]])



* `torch.ones()`: Creates a tensor filled with ones of the specified dimensions.

In [7]:
# All ones
ones = torch.ones(2,3)
print("TENSOR WITH ZEROS:\n\n",ones)

TENSOR WITH ZEROS:

 tensor([[1., 1., 1.],
        [1., 1., 1.]])



* `torch.rand()`: Generates a tensor with random numbers uniformly distributed between 0 and 1, based on the specified dimensions.

In [8]:
# random numbers
random = torch.rand(2,3)
print("TENSOR WITH ZEROS:\n\n",random)

TENSOR WITH ZEROS:

 tensor([[0.9444, 0.5652, 0.8827],
        [0.2991, 0.8212, 0.8234]])


### 1.3 - From a Sequence

For situations where you need to generate a sequence of data points, such as a range of values for testing a model's predictions, you can create a tensor directly from that sequence.

* `torch.arange()`: Creates a 1D tensor containing a range of numbers from the specified start value to one less than the specified stop value, incrementing (if positive) or decrementing (if negative) by the specified `step` value.

In [9]:
# Range of numbers
range_tensor = torch.arange(0,10,step = 1)
print("ARANGE TENSOR:", range_tensor)

ARANGE TENSOR: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## 2 - Reshaping & Manipulating

A very common source of errors in PyTorch projects is a mismatch between the shape of your input data and the shape your model expects. For instance, a model is typically designed to process a batch of data, so even if you want to make a single prediction, you must shape your input tensor to look like a batch of one. Mastering tensor reshaping is a key step toward building and debugging models effectively.

### 2.1 - Checking a Tensor's Dimensions

The first step to fixing a shape mismatch is to understand the current dimensions of your tensor. Checking the shape is your primary debugging tool. It tells you how many samples you have and how many features are in each sample.

* `torch.Tensor.shape`: An attribute that returns a `torch.Size` object detailing the size of the tensor along each dimension.

In [10]:
# A 2D tensor
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print("ORIGINAL TENSOR:\n\n",x)
print("\nTensor Shape:",x.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor Shape: torch.Size([2, 3])


### 2.2 - Changing a Tensor's Dimensions

Once you identify a shape mismatch, you need to correct it. A frequent task is adding a dimension to a single data sample to create a batch of size one for your model, or removing a dimension after a batch operation is complete.

* **Adding Dimension:** `torch.Tensor.unsqueeze()` inserts a new dimension at the specified index.
    * *Notice how the shape will change from `[2, 3]` to `[1, 2, 3]` and the tensor gets wrapped in an extra pair of square brackets `[]`*.

In [14]:
print("ORIGINAL TENSOR:\n\n",x)
print("\nTensor Shape:",x.shape)
print("-"*45)

#Add dimension
expanded = x.unsqueeze(0) # Add dimension ar index 0
print("\nTENSOR WITH ADDED DIMENSION AT INDEX 0:\n\n", expanded)
print("\nTesnsor shpae:",expanded.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor Shape: torch.Size([2, 3])
---------------------------------------------

TENSOR WITH ADDED DIMENSION AT INDEX 0:

 tensor([[[1, 2, 3],
         [4, 5, 6]]])

Tesnsor shpae: torch.Size([1, 2, 3])



* **Removing Dimension:** `torch.Tensor.squeeze()` removes dimensions of size 1.
    * *This reverses the unsqueeze operation, removing the `1` from the shape and taking away a pair of outer square brackets*.

In [20]:
print("EXPANDED TENSOR:\n\n",expanded)
print("\nTENSOR SHAPE:",expanded.shape)

#remove dimension
squeezed = expanded.squeeze()

print("TENSOR WITH DIMENSION REMOVED:\n\n", squeezed)
print("\nTensor Shape:", squeezed.shape)

EXPANDED TENSOR:

 tensor([[[1, 2, 3],
         [4, 5, 6]]])

TENSOR SHAPE: torch.Size([1, 2, 3])
TENSOR WITH DIMENSION REMOVED:

 tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor Shape: torch.Size([2, 3])


### 2.3 - Restructuring

Beyond just adding or removing dimensions, you may need to completely change a tensor's structure to match the requirements of a specific layer or operation within your neural network.

* **Reshaping:** `torch.Tensor.reshape()` changes the shape of a tensor to the specified dimensions.

In [24]:
print("ORIGINAL TENSOR:\n\n",x)
print("\nTENSOR SHAPE:",x.shape)
print("="*45)

#reshape
reshaped = x.reshape(3,2)
print("\nAFTER PERFORMING RESHAPE(2,3):\n\n",reshaped)
print("\nTENSOR SHAPE:",reshaped.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])

AFTER PERFORMING RESHAPE(2,3):

 tensor([[1, 2],
        [3, 4],
        [5, 6]])

TENSOR SHAPE: torch.Size([3, 2])


* **Transposing:** `torch.Tensor.transpose()` swaps the specified dimensions of a tensor.

In [33]:
print("ORIGINAL TENSOR:\n\n",x)
print("\nTENSOR SHAPE:",x.shape)
print("="*45)

#transpose
transposed = x.transpose(0,1)

print("\nAFTER PERFORMING TRANSPOSE(0,1):\n\n",transposed)
print("\nTENSOR SHAPE:",transposed.shape)


ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

TENSOR SHAPE: torch.Size([3, 3])

AFTER PERFORMING TRANSPOSE(0,1):

 tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

TENSOR SHAPE: torch.Size([3, 3])


### 2.4 - Combining Tensors

In the data preparation stage, you might need to combine data from different sources or merge separate batches into one larger dataset.

* `torch.cat()`: Joins a sequence of tensors along an existing dimension. Note: All tensors must have the same shape in dimensions other than the one being concatenated.

In [37]:
# Create two tensors to concatenate
tensor_a = torch.tensor([[1, 2],
                         [3, 4]])
tensor_b = torch.tensor([[5, 6],
                         [7, 8]])
# concatenated along columns (dim=1)
concatenated_tensors = torch.cat((tensor_a, tensor_b),dim = 1)
print('Tensor A:\n\n', tensor_a)
print('\nTensor B:\n\n', tensor_b)
print("="*45)
print("\nConcatenated Tensor (dim=1):\n\n",concatenated_tensors)

# concatenated along rows (dim=0)
concatenated_tensors = torch.cat((tensor_a, tensor_b),dim = 0)
print('Tensor A:\n\n', tensor_a)
print('\nTensor B:\n\n', tensor_b)
print("="*45)
print("\nConcatenated Tensor (dim=0):\n\n",concatenated_tensors)


Tensor A:

 tensor([[1, 2],
        [3, 4]])

Tensor B:

 tensor([[5, 6],
        [7, 8]])

Concatenated Tensor (dim=1):

 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
Tensor A:

 tensor([[1, 2],
        [3, 4]])

Tensor B:

 tensor([[5, 6],
        [7, 8]])

Concatenated Tensor (dim=0):

 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


## 3 - Indexing & Slicing

After you have your data in a tensor, you will often need to access specific parts of it. Whether you are grabbing a single prediction to inspect its value, separating your input features from your labels, or selecting a subset of data for analysis, indexing and slicing are the tools for the job.

### 3.1 - Accessing Elements

These are the fundamental techniques for getting data out of a tensor, working very similarly to how you would access elements in a standard Python list.

* **Standard Indexing**: Accessing single elements or entire rows using integer indices (e.g., `x[0]`, `x[1, 2]`).

In [42]:
# Create a 3x4 tensor
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("Original Tensor:\n\n",x)
print("Tensor Shape",x.shape)
print("="*45)

#Get a single element at row 1,column 2
single_element_tensor = x[1,2]
print("\nINDEXING SINGLE ELEMENT AT [1,2]", single_element_tensor)
print("="*45)

#Get the entire second row (index 1)
second_row = x[1]
print("\nINDEXING THE ENTIRE ROW[1]:", second_row)
print("="*45)

# last row
last_row = x[-1]
print("\nINDEXING ENTIRE LAST ROW([-1]):",last_row,"\n")

Original Tensor:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
Tensor Shape torch.Size([3, 4])

INDEXING SINGLE ELEMENT AT [1,2] tensor(7)

INDEXING THE ENTIRE ROW[1]: tensor([5, 6, 7, 8])

INDEXING ENTIRE LAST ROW([-1]): tensor([ 9, 10, 11, 12]) 





* **Slicing**: Extracting sub-tensors using `[start:end:step]` notation (e.g., `x[:2, ::2]`).
    * *Note: The `end` index itself is not included in the slice.*
* Slicing can be used to access entire columns.
* x[row_slice, :]
* x[:, column_slice]
* ::-1 → reverse

In [53]:
print("ORIGINAL TENSOR:\n\n",x)
print("="*55)

#get the frist two rows
first_two_rows = x[0:2]
print("\nSLICING FIRST TWO ROWS ([0:2]):\n\n",first_two_rows)
print("="*55)

#get the third column of all rows
third_column = x[:,2]
print("\nSLICING THIRD COLUMN ([]:,2])\n\n",third_column)
print("="*55)

#every other column
every_other_col = x[:,::2]

print("\nEVERY OTHER COLUMN ([:,::2]):\n\n",every_other_col)
print("="*55)
#last column
last_col = x[:,-1]
print("\nLAST COLUMN ([:,-1]):",last_col,"\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

SLICING FIRST TWO ROWS ([0:2]):

 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

SLICING THIRD COLUMN ([]:,2])

 tensor([ 3,  7, 11])

EVERY OTHER COLUMN ([:,::2]):

 tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])

LAST COLUMN ([:,-1]): tensor([ 4,  8, 12]) 



* Combining Indexing & Slicing

In [55]:
print("ORIGINAL TENSOR:\n\n",x)
print("="*55)
# combining slicing and indexing (First two rows,last two columns)
combined = x[0:2 , 2:]
print("\nFrist two rows, last teo cols ([0:2, 2:]):\n\n", combined)

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Frist two rows, last teo cols ([0:2, 2:]):

 tensor([[3, 4],
        [7, 8]])


<br>

* **`.item()`**: Extracts the value from a single-element tensor as a standard Python number.

In [63]:
print("SINGLE_ELEMENT TENSOR:", single_element_tensor)
print("="*45)

# extract the value from a single element tensor as a standart python number
value = single_element_tensor.item()

print("\n.item() Python number extracted:",value)
print("Type:",type(value))

SINGLE_ELEMENT TENSOR: tensor(7)

.item() Python number extracted: 7
Type: <class 'int'>


### 3.2 - Advanced Indexing

For more complex data selection, such as filtering your dataset based on one or more conditions, you can use advanced indexing techniques.

* **Boolean Masking**: Using a boolean tensor to select elements that meet a certain condition (e.g., `x[x > 5]`).

In [64]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Boolean indexing using logical comparisons
mask = x > 6
print("MASK (Values > 6):\n\n",mask,"\n")

# Applying boolean mask
mask_applied = x[mask]
print("Values after applying mask:",mask_applied,"\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------
MASK (Values > 6):

 tensor([[False, False, False, False],
        [False, False,  True,  True],
        [ True,  True,  True,  True]]) 

Values after applying mask: tensor([ 7,  8,  9, 10, 11, 12]) 





* **Fancy Indexing**: Using a tensor of indices to select specific elements in a non-contiguous way.

*	Fancy indexing lets you pick arbitrary elements.
*	None (or unsqueeze) adds a dimension so broadcasting works.
*	PyTorch then creates a grid of (row, col) pairs.
*	You get a submatrix of exactly those coordinates.

In [70]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# Fancy indexing

#Get first and third rows
row_indices = torch.tensor([0,2])

#Get secong and fourth columns
col_indices = torch.tensor([1,3])

#Gets values at (0,1), (0,3), (2,1), (2,3)
get_values = x[row_indices[:, None], col_indices]

print("\nSPECIFIC ELEMENTS USING INDICES:\n\n",get_values,"\n")


ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

SPECIFIC ELEMENTS USING INDICES:

 tensor([[ 2,  4],
        [10, 12]]) 

