In [ ]:
import torch
import torch.nn as nn
distances = torch.tensor([[3.0],[4.0],[1.5],[6.5]],dtype=torch.float32)
print(distances.shape) # batch size = 4, no_of_features = 1
simple_model = nn.Linear(1,1) #Expects 1 feature per sample
output = simple_model(distances)

torch.Size([4, 1])


In [8]:
distances = torch.tensor([[3.0,7.0,4.0],[3.5,7.5,4.2]])
print(distances.shape)
simple_model = nn.Linear(1,1)
#output = simple_model(distances) shape mismatches 

torch.Size([2, 3])


# Creating Tensors

In [9]:
my_distances = [[3.0],[7.0],[12.0],[18.0]]
tensor_from_list = torch.tensor(my_distances)
print(tensor_from_list.shape)

torch.Size([4, 1])


In [ ]:
import numpy as np
numpy_array = np.array([1.0,2.0,3.0])
tensor_from_numpy = torch.from_numpy(numpy_array)
print(tensor_from_numpy.shape)
tensor_from_numpy[1] = 5.0 #shares memory,if we change one the others change too, Reference 
numpy_array

torch.Size([3])


array([1., 5., 3.])

In [17]:
zeros = torch.zeros(3,3) # 3x3 tensor of zeros
ones = torch.ones(2,4) #2x4 tensor of ones
reandom = torch.rand(5,5) #5x5 tensor with random values
print(zeros)
print(ones)
print(reandom)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.5109, 0.0739, 0.4677, 0.8004, 0.3114],
        [0.6027, 0.5512, 0.5391, 0.6954, 0.8291],
        [0.2963, 0.6981, 0.0081, 0.2885, 0.6348],
        [0.7293, 0.2933, 0.6305, 0.9789, 0.1956],
        [0.9025, 0.6287, 0.6629, 0.6053, 0.8664]])


In [ ]:
single_distance = torch.tensor(35.0)
print(single_distance.shape)
simple_model = nn.Linear(1,1) # expecs (batch_size,1)
with_batch = single_distance.unsqueeze(0) #added batch dim
print(f"after Squeeing: {with_batch.shape}")
ready_for_model = with_batch.unsqueeze(1) # now ready
print(f"After Unsqueeze: {ready_for_model.shape}")

torch.Size([])
after Squeeing: torch.Size([1])
After Unsqueeze: torch.Size([1, 1])


In [29]:
# removing all dimension of size 1
# clean up after batching
squeezed = ready_for_model.squeeze()
print(squeezed.shape)

torch.Size([])


# Indexing and Slicing

In [ ]:
predictions = torch.tensor([[14.9],[24.1],[35.6],[45.2]])
first = predictions[0]
print(first)
first_three = predictions[:3]
print(first_three)
#use item() to get a python number
value = predictions[0].item() # works on with tensor with exactly one element
print(value)

tensor([14.9000])
tensor([[14.9000],
        [24.1000],
        [35.6000]])
14.899999618530273


In [37]:
data = torch.tensor([[3,8,9],
                    [4,5,6],
                    [7,4,3]])
distances = data[:, 0]
print(distances)

tensor([3, 4, 7])
